language: objective-c
before_install:
    - brew update
    - brew install xctool
    - brew install python
    - bundle install
    - pod install
    - sudo pip install cpp-coveralls --use-mirrors
script:
    - rake
after_success:
  - coveralls -e UnitTests -e Pods -e ProtocolTests -e Demo

