language: objective-c
before_install:
    - brew update
    - which -s xctool || brew link xctool || brew install xctool
    - which -s pip || brew link python || brew install python
    - bundle install
    - pod install
    - sudo pip install cpp-coveralls --use-mirrors
script:
    - rake
after_success:
  - coveralls -e UnitTests -e Pods -e ProtocolTests -e Demo

