language: objective-c
before_install:
    - brew update
    - brew uninstall xctool
    - brew install xctool
    - brew install python
    - brew install lcov
    - bundle install
    - pod install
    - sudo pip install cpp-coveralls --use-mirrors
script:
    - rake
after_success:
  - coveralls

