language: objective-c
before_install:
    - brew update
    - brew uninstall xctool
    - brew install xctool
    - bundle install
    - pod install
    - sudo pip install cpp-coveralls --use-mirrors
script:
    - rake
after_success:
  - coveralls -r Build/ErnKit.build/Objects-normal/i386

